-- MySQL Script generated by MySQL Workbench
-- 09/24/16 19:03:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema codegenerator
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codegenerator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codegenerator` DEFAULT CHARACTER SET utf8 ;
USE `codegenerator` ;

-- -----------------------------------------------------
-- Table `codegenerator`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codegenerator`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_mail` VARCHAR(45) NOT NULL,
  `user_role` VARCHAR(5) NULL,
  `user_password` VARCHAR(30) NOT NULL,
  `user_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `user_mail_UNIQUE` (`user_mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codegenerator`.`lock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codegenerator`.`lock` (
  `id_lock` INT NOT NULL AUTO_INCREMENT,
  `lock_name` VARCHAR(15) NOT NULL,
  `lock_cells` INT(10) NOT NULL,
  `lock_range` INT(10) NOT NULL,
  `lock_key` VARCHAR(10) NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_lock`, `user_id_user`),
  INDEX `fk_lock_user_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_lock_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `codegenerator`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
